### ISSUE TITLE
MWAA 2.2.2 constraints file

### ISSUE THREAD

**Issue by firewall413** [aws-samples/emr-serverless-samples#40] opened 2022-11-25 17:00 UTC
How are you able to install the emr_serverless package on MWAA 2.2.2 using the [official](https://docs.aws.amazon.com/mwaa/latest/userguide/best-practices-dependencies.html) [constraints](https://raw.githubusercontent.com/apache/airflow/constraints-2.2.2/constraints-3.7.txt) file:

The emr_serverless operator depends on **boto3>=1.23.9**

While MWAA 2.2.2 has the following constraints:
**boto3==1.18.65
boto==2.49.0
botocore==1.21.65**

**Comment by dacort** [comment] 2022-11-25 18:09
Dupe of #37 - That said, I need to look into this more as it seems people are having issues but see https://github.com/aws-samples/emr-serverless-samples/issues/37#issuecomment-1325578459 for a workaround using official airflow amazon provider.

**Closed as completed by dacort** 2022-11-25 18:09 UTC
